export enum ACTIONS {
  SET_CATALOG = 'SET_CATALOG',
  GET_CATALOG = 'GET_CATALOG',

  SET_MEN_CATALOG = 'SET_MEN_CATALOG',
  GET_MEN_CATALOG = 'GET_MEN_CATALOG',

  SET_WOMEN_CATALOG = 'SET_WOMEN_CATALOG',
  GET_WOMEN_CATALOG = 'GET_WOMEN_CATALOG',

  SET_JEWELRY_CATALOG = 'SET_JEWELRY_CATALOG',
  GET_JEWELRY_CATALOG = 'GET_JEWELRY_CATALOG',

  SET_ELECTRONICS_CATALOG = 'SET_ELECTRONICS_CATALOG',
  GET_ELECTRONICS_CATALOG = 'GET_ELECTRONICS_CATALOG',

  SET_SINGLE_ITEM = 'SET_SINGLE_ITEM',
  GET_SINGLE_ITEM = 'GET_SINGLE_ITEM',

  SET_CART = 'SET_CART',
  GET_CART = 'GET_CART',
  DELETE_ITEM = 'DELETE_ITEM',
  REMOVE_CART = 'REMOVE_CART',
  INCREMENT_ITEM_QUANTITY = 'INCREMENT_ITEM_QUANTITY',
  DECREMENT_ITEM_QUANTITY = 'DECREMENT_ITEM_QUANTITY',
}
